#! /bin/sh
./getTitle.pl http://t.co/egX61Qun
./getTitle.pl http://t.co/0amYik3Q
./getTitle.pl http://t.co/0jmiOSpR
./getTitle.pl http://t.co/0TySUsk9
./getTitle.pl http://t.co/104F4kDA
./getTitle.pl http://t.co/12GuuvoG
./getTitle.pl http://t.co/17dO8CyN
./getTitle.pl http://t.co/1dvnky1z
./getTitle.pl http://t.co/1iXFNfVp
./getTitle.pl http://t.co/1MvhydvX
./getTitle.pl http://t.co/1vj85x9h
./getTitle.pl http://t.co/22hjZuPt
./getTitle.pl http://t.co/2AjhSE77
./getTitle.pl http://t.co/2IWUnoMf
./getTitle.pl http://t.co/2kMRK0BH
./getTitle.pl http://t.co/2SP7Pnji
./getTitle.pl http://t.co/2ZMbKF7u
./getTitle.pl http://t.co/3epsVLed
./getTitle.pl http://t.co/3Ez8mYLw
./getTitle.pl http://t.co/3Fs2PsE1
./getTitle.pl http://t.co/3kZCSNnF
./getTitle.pl http://t.co/3SpEy2DM
./getTitle.pl http://t.co/3v89ZBJB
./getTitle.pl http://t.co/3vWomHbZ
./getTitle.pl http://t.co/4b0CHXwg
./getTitle.pl http://t.co/4eRH7vLO
./getTitle.pl http://t.co/4jGAxVfb
./getTitle.pl http://t.co/5DNKWt1b
./getTitle.pl http://t.co/5dY0NeqZ
./getTitle.pl http://t.co/5fRFzVcM
./getTitle.pl http://t.co/5fZ7HVLx
./getTitle.pl http://t.co/5IrmADFm
./getTitle.pl http://t.co/5KcOkYoo
./getTitle.pl http://t.co/5nd3vKoL
./getTitle.pl http://t.co/5UxWvX3k
./getTitle.pl http://t.co/6FpXPOXJ
./getTitle.pl http://t.co/6HnJ08DS
./getTitle.pl http://t.co/6lcuVeqj
./getTitle.pl http://t.co/6liDKcxn
./getTitle.pl http://t.co/6rwwY0oZ
./getTitle.pl http://t.co/6WpsmMFu
./getTitle.pl http://t.co/77MUFbZa
./getTitle.pl http://t.co/7QDpna5T
./getTitle.pl http://t.co/7s2V34df
./getTitle.pl http://t.co/7wTdX1G2
./getTitle.pl http://t.co/7zon8zel
./getTitle.pl http://t.co/8b0qroas
./getTitle.pl http://t.co/8NvUE1mN
./getTitle.pl http://t.co/8ycR3wrG
./getTitle.pl http://t.co/8ZJ2uPtg
./getTitle.pl http://t.co/98xM9PVR
./getTitle.pl http://t.co/99HSiwic
./getTitle.pl http://t.co/9bEjn8In
./getTitle.pl http://t.co/9kg7VSq
./getTitle.pl http://t.co/9P7XGawx
./getTitle.pl http://t.co/9PIpVnaF
./getTitle.pl http://t.co/9YNpRn6T
./getTitle.pl http://t.co/9ZpYQT9Y
./getTitle.pl http://t.co/a35K2jxz
./getTitle.pl http://t.co/A5t0aZJj
./getTitle.pl http://t.co/ABSw1WAq
./getTitle.pl http://t.co/afi3S1xG
./getTitle.pl http://t.co/agxGqRVc
./getTitle.pl http://t.co/APtWkB68
./getTitle.pl http://t.co/B29D1Edx
./getTitle.pl http://t.co/baE1xdLg
./getTitle.pl http://t.co/bcXGihoF
./getTitle.pl http://t.co/BD04L0mf
./getTitle.pl http://t.co/bDb39ojJ
./getTitle.pl http://t.co/biOlkyxO
./getTitle.pl http://t.co/BiZL1NWe
./getTitle.pl http://t.co/bKvk2GJi
./getTitle.pl http://t.co/BLpkwixb
./getTitle.pl http://t.co/Bn9JDxNK
./getTitle.pl http://t.co/bo8YHheq
./getTitle.pl http://t.co/BTDB5P2w
./getTitle.pl http://t.co/bXrshr8y
./getTitle.pl http://t.co/Ccw1rDbP
./getTitle.pl http://t.co/Cgyoe6Jy
./getTitle.pl http://t.co/cj1sNqYT
./getTitle.pl http://t.co/clFBsyc2
./getTitle.pl http://t.co/ctPD8a5a
./getTitle.pl http://t.co/Cw7GUQbn
./getTitle.pl http://t.co/CXAp3sZn
./getTitle.pl http://t.co/cXk958pB
./getTitle.pl http://t.co/d0CLJQWD
./getTitle.pl http://t.co/diDKRuQw
./getTitle.pl http://t.co/DJQru0fz
./getTitle.pl http://t.co/DKmGbQui
./getTitle.pl http://t.co/DmbOb93g
./getTitle.pl http://t.co/dmd7NADg
./getTitle.pl http://t.co/E0FBOesX
./getTitle.pl http://t.co/E16cSYqh
./getTitle.pl http://t.co/e2qx3oiO
./getTitle.pl http://t.co/E302aWXn
./getTitle.pl http://t.co/E5UZMNsf
./getTitle.pl http://t.co/E5vjQ7xt
./getTitle.pl http://t.co/e9cCcE0x
./getTitle.pl http://t.co/ebqUhvoj
./getTitle.pl http://t.co/eEeMVGRI
./getTitle.pl http://t.co/EepeWkJc
./getTitle.pl http://t.co/eHCi7dhs
./getTitle.pl http://t.co/ePhIvrxR
./getTitle.pl http://t.co/ETe2IDAT
./getTitle.pl http://t.co/EVDYRo99
./getTitle.pl http://t.co/EVm4xo01
./getTitle.pl http://t.co/EXH6iMHW
./getTitle.pl http://t.co/Ezjbqko8
./getTitle.pl http://t.co/F12pfIpA
./getTitle.pl http://t.co/F3kGW42l
./getTitle.pl http://t.co/FavKSkwX
./getTitle.pl http://t.co/FB1oBTOA
./getTitle.pl http://t.co/fBBpn0e1
./getTitle.pl http://t.co/FEj489Dc
./getTitle.pl http://t.co/FFlXAVJV
./getTitle.pl http://t.co/fGmmJ76d
./getTitle.pl http://t.co/FhAp82f4
./getTitle.pl http://t.co/fHQ3dou4
./getTitle.pl http://t.co/FkgvpMfN
./getTitle.pl http://t.co/fpPcTm8O
./getTitle.pl http://t.co/fvF6kbkk
./getTitle.pl http://t.co/Fx8oCxYs
./getTitle.pl http://t.co/FxoLOphy
./getTitle.pl http://t.co/FYjdBqU0
./getTitle.pl http://t.co/g0raxtKs
./getTitle.pl http://t.co/GHoVcBhf
./getTitle.pl http://t.co/giikOCjG
./getTitle.pl http://t.co/giLrVQRD
./getTitle.pl http://t.co/gjiinME6
./getTitle.pl http://t.co/gPXi8Tsl
./getTitle.pl http://t.co/GSIIt7H9
./getTitle.pl http://t.co/gxDfyjq8
./getTitle.pl http://t.co/gyTOXAmO
./getTitle.pl http://t.co/H4b5aixj
./getTitle.pl http://t.co/HbI04GNb
./getTitle.pl http://t.co/hc0r2DuM
./getTitle.pl http://t.co/hDuKQ2dL
./getTitle.pl http://t.co/hFvATZ1J
./getTitle.pl http://t.co/hh95rzoQ
./getTitle.pl http://t.co/Hnh9TwTQ
./getTitle.pl http://t.co/hpqUgFvM
./getTitle.pl http://t.co/HpwDdMgl
./getTitle.pl http://t.co/Hqsu05fL
./getTitle.pl http://t.co/hRBMZv3w
./getTitle.pl http://t.co/hRQVx7cl
./getTitle.pl http://t.co/hrrheEa6
./getTitle.pl http://t.co/hs6bIAsH
./getTitle.pl http://t.co/i6EbYL4c
./getTitle.pl http://t.co/i7lyDJwU
./getTitle.pl http://t.co/iAD3aAxn
./getTitle.pl http://t.co/IfUngRMZ
./getTitle.pl http://t.co/iggRgHDT
./getTitle.pl http://t.co/Ih7dDMmC
./getTitle.pl http://t.co/IJXgOr9Z
./getTitle.pl http://t.co/IkCrXYmB
./getTitle.pl http://t.co/Il2RPSlb
./getTitle.pl http://t.co/Il85gxnc
./getTitle.pl http://t.co/ImsL2PhV
./getTitle.pl http://t.co/ipnc05xG
./getTitle.pl http://t.co/iQ7ltJsu
./getTitle.pl http://t.co/IX8O5ow3
./getTitle.pl http://t.co/iY8tk5NP
./getTitle.pl http://t.co/IZMA1XTS
./getTitle.pl http://t.co/jadnpupb
./getTitle.pl http://t.co/jccibPp4
./getTitle.pl http://t.co/jEpALKWO
./getTitle.pl http://t.co/jHYMsveC
./getTitle.pl http://t.co/jiX9OU5i
./getTitle.pl http://t.co/jIXs14Qo
./getTitle.pl http://t.co/jk5toJSR
./getTitle.pl http://t.co/jNj2sqiW
./getTitle.pl http://t.co/jQqRxxQq
./getTitle.pl http://t.co/Jwaqidar
./getTitle.pl http://t.co/jYRsfPCA
./getTitle.pl http://t.co/k9ivAFaf
./getTitle.pl http://t.co/kDeIvlzw
./getTitle.pl http://t.co/KdV4RXTG
./getTitle.pl http://t.co/kF5MJFyw
./getTitle.pl http://t.co/Ki0s0hH3
./getTitle.pl http://t.co/KOo7rkQ2
./getTitle.pl http://t.co/KRpkKAmA
./getTitle.pl http://t.co/kUc2BULQ
./getTitle.pl http://t.co/kUV9HpIy
./getTitle.pl http://t.co/kVWuxlk7
./getTitle.pl http://t.co/kYL534W7
./getTitle.pl http://t.co/L81xi9BS
./getTitle.pl http://t.co/lAgiD1u9
./getTitle.pl http://t.co/LbveaSEW
./getTitle.pl http://t.co/lEgBgcdU
./getTitle.pl http://t.co/LKSJ62hH
./getTitle.pl http://t.co/LqR28Anj
./getTitle.pl http://t.co/ls071DyP
./getTitle.pl http://t.co/LVd4RiTe
./getTitle.pl http://t.co/lVit1uud
./getTitle.pl http://t.co/mAnznUkT
./getTitle.pl http://t.co/mBWR90Ac
./getTitle.pl http://t.co/mcI4qMjQ
./getTitle.pl http://t.co/mLWIbS9M
./getTitle.pl http://t.co/mmgF32tV
./getTitle.pl http://t.co/MQKC8gYU
./getTitle.pl http://t.co/MSQS8m2O
./getTitle.pl http://t.co/mY75Hi24
./getTitle.pl http://t.co/N5ms9ZPk
./getTitle.pl http://t.co/N5UZzA9F
./getTitle.pl http://t.co/n8SZUDeM
./getTitle.pl http://t.co/n9KW9UQe
./getTitle.pl http://t.co/N9nMFOu5
./getTitle.pl http://t.co/NDKxL5E4
./getTitle.pl http://t.co/NfwJt9Dn
./getTitle.pl http://t.co/NgYvhzr4
./getTitle.pl http://t.co/Nh7jwwT7
./getTitle.pl http://t.co/nonN3eIW
./getTitle.pl http://t.co/NwPS1KGy
./getTitle.pl http://t.co/NWsp324U
./getTitle.pl http://t.co/O3TzrtBp
./getTitle.pl http://t.co/OBCtBN8D
./getTitle.pl http://t.co/OEfQBbHL
./getTitle.pl http://t.co/OeFvZXHD
./getTitle.pl http://t.co/ofIvNFVd
./getTitle.pl http://t.co/ohec5Zt0
./getTitle.pl http://t.co/OJYgRlwh
./getTitle.pl http://t.co/OlhYX7zV
./getTitle.pl http://t.co/oNwzC63L
./getTitle.pl http://t.co/ootL9XTW
./getTitle.pl http://t.co/owjaUU65
./getTitle.pl http://t.co/P4QvFMsi
./getTitle.pl http://t.co/p5Z2WF63
./getTitle.pl http://t.co/PaOzBxv0
./getTitle.pl http://t.co/pEq7f7cI
./getTitle.pl http://t.co/pJ0b1M9e
./getTitle.pl http://t.co/pk5RGotx
./getTitle.pl http://t.co/PLAiq7Vz
./getTitle.pl http://t.co/Pnpf1I7N
./getTitle.pl http://t.co/pstlPsTF
./getTitle.pl http://t.co/pwgM1yP3
./getTitle.pl http://t.co/pXIL36kA
./getTitle.pl http://t.co/Q1EF5jHz
./getTitle.pl http://t.co/QaeFw4hp
./getTitle.pl http://t.co/qEKJw9Hn
./getTitle.pl http://t.co/QmkDqHG8
./getTitle.pl http://t.co/qriquOxn
./getTitle.pl http://t.co/QTZy6Th9
./getTitle.pl http://t.co/racZGenj
./getTitle.pl http://t.co/resxnbMT
./getTitle.pl http://t.co/REwNEa9B
./getTitle.pl http://t.co/rjciAMbT
./getTitle.pl http://t.co/rQoA2ejQ
./getTitle.pl http://t.co/RV7T0bZo
./getTitle.pl http://t.co/RYTREDYh
./getTitle.pl http://t.co/rzHlGCMc
./getTitle.pl http://t.co/S2favUOy
./getTitle.pl http://t.co/sfa38vl2
./getTitle.pl http://t.co/Sg54vA8h
./getTitle.pl http://t.co/sJb5yEc4
./getTitle.pl http://t.co/Smm3Do29
./getTitle.pl http://t.co/sOXuyFLG
./getTitle.pl http://t.co/sP3a1kPt
./getTitle.pl http://t.co/sPDeeloj
./getTitle.pl http://t.co/suBdERHo
./getTitle.pl http://t.co/sxjnyotU
./getTitle.pl http://t.co/tAdS4Kqg
./getTitle.pl http://t.co/TaWp9BXo
./getTitle.pl http://t.co/TBLdWBzi
./getTitle.pl http://t.co/TCQX6Vas 
./getTitle.pl http://t.co/TehR3xmm
./getTitle.pl http://t.co/Tej3kjUp
./getTitle.pl http://t.co/THb2yVn6
./getTitle.pl http://t.co/Ti8yqLYx
./getTitle.pl http://t.co/TjvWlAY8
./getTitle.pl http://t.co/tlEOyfLr
./getTitle.pl http://t.co/TQ05ThYz
./getTitle.pl http://t.co/tWI8sAMF
./getTitle.pl http://t.co/u5UcHlt3
./getTitle.pl http://t.co/U9QgF5CJ
./getTitle.pl http://t.co/UBaVt768
./getTitle.pl http://t.co/uIaPvqSD
./getTitle.pl http://t.co/UJJFTFd9
./getTitle.pl http://t.co/UnmBFBWv
./getTitle.pl http://t.co/urtbGtWC
./getTitle.pl http://t.co/utuqYMsV
./getTitle.pl http://t.co/uVIzTAtB
./getTitle.pl http://t.co/V0XraBht
./getTitle.pl http://t.co/V1Fel3MR
./getTitle.pl http://t.co/V6imBdeb
./getTitle.pl http://t.co/vFcQ1bkW
./getTitle.pl http://t.co/VjHdzS8o
./getTitle.pl http://t.co/VMkNzu0K
./getTitle.pl http://t.co/VqLPWDka
./getTitle.pl http://t.co/Vwjyop21
./getTitle.pl http://t.co/vXqUY3eL
./getTitle.pl http://t.co/w7q6UyJ7
./getTitle.pl http://t.co/w85Z2Ccu
./getTitle.pl http://t.co/WBhCcrHz
./getTitle.pl http://t.co/wf7pjGWi
./getTitle.pl http://t.co/WgEXpUBf
./getTitle.pl http://t.co/WhiLUryR
./getTitle.pl http://t.co/wMojiFer
./getTitle.pl http://t.co/wu5L3fHR
./getTitle.pl http://t.co/WUyV0jzc
./getTitle.pl http://t.co/WWfzNDwU
./getTitle.pl http://t.co/wwToCquJ
./getTitle.pl http://t.co/WxQ81du8
./getTitle.pl http://t.co/WZ5tsYDQ
./getTitle.pl http://t.co/Xbg0Dlqo
./getTitle.pl http://t.co/XEXpZuKs
./getTitle.pl http://t.co/xfRfbGKe
./getTitle.pl http://t.co/xhWCcBOh
./getTitle.pl http://t.co/XKiQdBoY
./getTitle.pl http://t.co/XkuZTCfg
./getTitle.pl http://t.co/xmACaUYe
./getTitle.pl http://t.co/XNjKaDDW
./getTitle.pl http://t.co/xvoWpLVF
./getTitle.pl http://t.co/xwR0T8J9
./getTitle.pl http://t.co/XWrgIcnF
./getTitle.pl http://t.co/xZ7mxewR
./getTitle.pl http://t.co/XZtNMXnW
./getTitle.pl http://t.co/y2IE4Qis
./getTitle.pl http://t.co/yCmnVtZZ
./getTitle.pl http://t.co/yDTjjr7R
./getTitle.pl http://t.co/ygsCccdt
./getTitle.pl http://t.co/YhSONfrx
./getTitle.pl http://t.co/YLazoe43
./getTitle.pl http://t.co/Ynyxww7E
./getTitle.pl http://t.co/YOMsOcfC
./getTitle.pl http://t.co/z0P1MuRs
./getTitle.pl http://t.co/z8Qx59iD
./getTitle.pl http://t.co/zfpPHOTa
./getTitle.pl http://t.co/ZqnhR8Q5
./getTitle.pl http://t.co/zrQL14eO
./getTitle.pl http://t.co/ZxxXZHyk
./getTitle.pl http://t.co/ZYycHOwS
./getTitle.pl https://t.co/5ubYs2PH 
./getTitle.pl https://t.co/L0DgLZej
./getTitle.pl https://t.co/VUZv4d6I

